
# turn on basic auth

spring:
  security:
    user:
      name: ${broker.filter.user}
      password: ${broker.filter.password}


# turn on actuator endpoints protected by basic auth
management:
  endpoint:
    beans:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    httptrace:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true

# make enabled endpoints accessible over web. setting "*" seems to expose also non enabled endpoints
  endpoints:
    web:
      exposure:
        include: "beans,info,health,httptrace,loggers,metrics"