logging:
  level:
    ROOT: INFO
    #org.apache.http: DEBUG

security:
  user:
    name: ${filtered.broker.credentials.name}
    password: ${filtered.broker.credentials.password}

zuul:
 routes:
  filtered-broker:
      path: /**
      url: ${filtered.broker.url}/
      sensitiveHeaders: Cookie,Set-Cookie #excludes Authorization
